// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaNominaADC.Datos;

#nullable disable

namespace SistemaNominaADC.Datos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306004129_ConceptosEmpleadoYAfectacionBases")]
    partial class ConceptosEmpleadoYAfectacionBases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Asistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsistencia"));

                    b.Property<bool?>("Ausencia")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("date");

                    b.Property<DateTime?>("HoraEntrada")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("HoraSalida")
                        .HasColumnType("datetime");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Justificacion")
                        .HasColumnType("text");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.ToTable("Asistencia", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Bitacora", b =>
                {
                    b.Property<int>("IdBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBitacora"));

                    b.Property<string>("Accion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdBitacora");

                    b.ToTable("Bitacora", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("IdEstado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdDepartamento");

                    b.HasIndex("IdEstado");

                    b.ToTable("Departamento", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.DepartamentoJefatura", b =>
                {
                    b.Property<int>("IdDepartamentoJefatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamentoJefatura"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("TipoJefatura")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("VigenciaDesde")
                        .HasColumnType("date");

                    b.Property<DateTime?>("VigenciaHasta")
                        .HasColumnType("date");

                    b.HasKey("IdDepartamentoJefatura");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("DepartamentoJefatura", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdPuesto")
                        .HasColumnType("int");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPuesto");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.EmpleadoJerarquia", b =>
                {
                    b.Property<int>("IdEmpleadoJerarquia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleadoJerarquia"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdSupervisor")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("VigenciaDesde")
                        .HasColumnType("date");

                    b.Property<DateTime?>("VigenciaHasta")
                        .HasColumnType("date");

                    b.HasKey("IdEmpleadoJerarquia");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdSupervisor");

                    b.ToTable("EmpleadoJerarquia", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<int?>("Codigo")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool?>("EstadoActivo")
                        .HasColumnType("bit")
                        .HasColumnName("Estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdEstado");

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.FlujoEstado", b =>
                {
                    b.Property<int>("IdFlujoEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFlujoEstado"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdEstadoDestino")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstadoOrigen")
                        .HasColumnType("int");

                    b.Property<string>("RequiereRol")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.HasKey("IdFlujoEstado");

                    b.HasIndex("IdEstadoDestino");

                    b.HasIndex("IdEstadoOrigen");

                    b.HasIndex("Entidad", "Accion", "IdEstadoOrigen", "IdEstadoDestino")
                        .IsUnique()
                        .HasFilter("[IdEstadoOrigen] IS NOT NULL");

                    b.ToTable("FlujoEstado", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.GrupoEstado", b =>
                {
                    b.Property<int>("IdGrupoEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupoEstado"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdGrupoEstado");

                    b.ToTable("GrupoEstado", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.GrupoEstadoDetalle", b =>
                {
                    b.Property<int>("IdGrupoEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("Orden")
                        .HasColumnType("int");

                    b.HasKey("IdGrupoEstado", "IdEstado");

                    b.HasIndex("IdEstado");

                    b.ToTable("GrupoEstadoDetalle", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Incapacidad", b =>
                {
                    b.Property<int>("IdIncapacidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIncapacidad"));

                    b.Property<string>("ComentarioAprobacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ComentarioRevision")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ComentarioSolicitud")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoIncapacidad")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoCubierto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NombreDocumento")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RutaDocumento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("IdIncapacidad");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTipoIncapacidad");

                    b.ToTable("Incapacidad", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.ModoCalculoConceptoNomina", b =>
                {
                    b.Property<int>("IdModoCalculoConceptoNomina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModoCalculoConceptoNomina"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdModoCalculoConceptoNomina");

                    b.HasIndex("IdEstado");

                    b.ToTable("ModoCalculoConceptoNomina", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Notificacion", b =>
                {
                    b.Property<int>("IdNotificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNotificacion"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLectura")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Leida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UrlDestino")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("IdNotificacion");

                    b.ToTable("Notificacion", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.ObjetoSistema", b =>
                {
                    b.Property<int>("IdObjeto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdObjeto"));

                    b.Property<int>("IdGrupoEstado")
                        .HasColumnType("int");

                    b.Property<string>("NombreEntidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdObjeto");

                    b.HasIndex("IdGrupoEstado");

                    b.HasIndex("NombreEntidad")
                        .IsUnique();

                    b.ToTable("ObjetoSistema", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.ObjetoSistemaRol", b =>
                {
                    b.Property<int>("IdObjeto")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdObjeto", "RoleName");

                    b.ToTable("ObjetoSistemaRol", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("ComentarioAprobacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("FechaFin")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaInicio")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoPermiso")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdPermiso");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTipoPermiso");

                    b.ToTable("Permiso", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.PlanillaDetalle", b =>
                {
                    b.Property<int>("IdPlanillaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanillaDetalle"));

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdPlanilla")
                        .HasColumnType("int");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SalarioBruto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalDeducciones")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalIngresos")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPlanillaDetalle");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPlanilla");

                    b.ToTable("PlanillaDetalle", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.PlanillaDetalleConcepto", b =>
                {
                    b.Property<int>("IdDetalleConcepto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleConcepto"));

                    b.Property<int>("IdConceptoNomina")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdPlanillaDetalle")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdDetalleConcepto");

                    b.HasIndex("IdConceptoNomina");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPlanillaDetalle");

                    b.ToTable("PlanillaDetalleConcepto", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.PlanillaEncabezado", b =>
                {
                    b.Property<int>("IdPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPlanilla"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("date");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoPlanilla")
                        .HasColumnType("int");

                    b.Property<int?>("PeriodoAguinaldo")
                        .HasColumnType("int");

                    b.Property<DateTime>("PeriodoFin")
                        .HasColumnType("date");

                    b.Property<DateTime>("PeriodoInicio")
                        .HasColumnType("date");

                    b.HasKey("IdPlanilla");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTipoPlanilla");

                    b.ToTable("PlanillaEncabezado", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Puesto", b =>
                {
                    b.Property<int>("IdPuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPuesto"));

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPuesto");

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdEstado");

                    b.ToTable("Puesto", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.SolicitudHorasExtra", b =>
                {
                    b.Property<int>("IdSolicitudHorasExtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitudHorasExtra"));

                    b.Property<decimal?>("CantidadHoras")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ComentarioAprobacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("Fecha")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoHoraExtra")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdSolicitudHorasExtra");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdTipoHoraExtra");

                    b.ToTable("SolicitudHorasExtra", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.SolicitudVacaciones", b =>
                {
                    b.Property<int>("IdSolicitudVacaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitudVacaciones"));

                    b.Property<int?>("CantidadDias")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioAprobacion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ComentarioSolicitud")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("FechaFin")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaInicio")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.HasKey("IdSolicitudVacaciones");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.ToTable("SolicitudVacaciones", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.TipoConceptoNomina", b =>
                {
                    b.Property<int>("IdConceptoNomina")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConceptoNomina"));

                    b.Property<string>("CodigoConcepto")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("CodigoFormula")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<bool>("EsDeduccion")
                        .HasColumnType("bit");

                    b.Property<bool>("EsIngreso")
                        .HasColumnType("bit");

                    b.Property<string>("FormulaCalculo")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdModoCalculo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("OrdenCalculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("ValorFijo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ValorPorcentaje")
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("IdConceptoNomina");

                    b.HasIndex("CodigoConcepto")
                        .IsUnique()
                        .HasFilter("[CodigoConcepto] IS NOT NULL");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdModoCalculo");

                    b.ToTable("TipoConceptoNomina", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.TipoHoraExtra", b =>
                {
                    b.Property<int>("IdTipoHoraExtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoHoraExtra"));

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PorcentajePago")
                        .IsRequired()
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("IdTipoHoraExtra");

                    b.HasIndex("IdEstado");

                    b.ToTable("TipoHoraExtra", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.TipoIncapacidad", b =>
                {
                    b.Property<int>("IdTipoIncapacidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoIncapacidad"));

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoIncapacidad");

                    b.HasIndex("IdEstado");

                    b.ToTable("TipoIncapacidad", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.TipoPermiso", b =>
                {
                    b.Property<int>("IdTipoPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoPermiso"));

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoPermiso");

                    b.HasIndex("IdEstado");

                    b.ToTable("TipoPermiso", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.TipoPlanilla", b =>
                {
                    b.Property<int>("IdTipoPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoPlanilla"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdTipoPlanilla");

                    b.HasIndex("IdEstado");

                    b.ToTable("TipoPlanilla", (string)null);
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Vacaciones", b =>
                {
                    b.Property<int>("IdVacaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVacaciones"));

                    b.Property<int?>("DiasRestantes")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("int");

                    b.HasKey("IdVacaciones");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.ToTable("Vacaciones", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaNominaADC.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Asistencia", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Departamento", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.DepartamentoJefatura", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaNominaADC.Entidades.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Empleado", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaNominaADC.Entidades.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("IdPuesto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.EmpleadoJerarquia", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaNominaADC.Entidades.Empleado", "Supervisor")
                        .WithMany()
                        .HasForeignKey("IdSupervisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.FlujoEstado", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Estado", "EstadoDestino")
                        .WithMany()
                        .HasForeignKey("IdEstadoDestino")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaNominaADC.Entidades.Estado", "EstadoOrigen")
                        .WithMany()
                        .HasForeignKey("IdEstadoOrigen")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EstadoDestino");

                    b.Navigation("EstadoOrigen");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.GrupoEstadoDetalle", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaNominaADC.Entidades.GrupoEstado", "GrupoEstado")
                        .WithMany()
                        .HasForeignKey("IdGrupoEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("GrupoEstado");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Incapacidad", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaNominaADC.Entidades.TipoIncapacidad", "TipoIncapacidad")
                        .WithMany()
                        .HasForeignKey("IdTipoIncapacidad")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empleado");

                    b.Navigation("Estado");

                    b.Navigation("TipoIncapacidad");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.ModoCalculoConceptoNomina", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.ObjetoSistema", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.GrupoEstado", "GrupoEstado")
                        .WithMany()
                        .HasForeignKey("IdGrupoEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoEstado");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.ObjetoSistemaRol", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.ObjetoSistema", "ObjetoSistema")
                        .WithMany()
                        .HasForeignKey("IdObjeto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ObjetoSistema");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Permiso", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaNominaADC.Entidades.TipoPermiso", "TipoPermiso")
                        .WithMany()
                        .HasForeignKey("IdTipoPermiso")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empleado");

                    b.Navigation("Estado");

                    b.Navigation("TipoPermiso");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.PlanillaDetalle", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaNominaADC.Entidades.PlanillaEncabezado", "Planilla")
                        .WithMany()
                        .HasForeignKey("IdPlanilla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Estado");

                    b.Navigation("Planilla");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.PlanillaDetalleConcepto", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.TipoConceptoNomina", "TipoConceptoNomina")
                        .WithMany()
                        .HasForeignKey("IdConceptoNomina")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaNominaADC.Entidades.PlanillaDetalle", "PlanillaDetalle")
                        .WithMany()
                        .HasForeignKey("IdPlanillaDetalle")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("PlanillaDetalle");

                    b.Navigation("TipoConceptoNomina");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.PlanillaEncabezado", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaNominaADC.Entidades.TipoPlanilla", "TipoPlanilla")
                        .WithMany()
                        .HasForeignKey("IdTipoPlanilla")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("TipoPlanilla");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Puesto", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.SolicitudHorasExtra", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaNominaADC.Entidades.TipoHoraExtra", "TipoHoraExtra")
                        .WithMany()
                        .HasForeignKey("IdTipoHoraExtra")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empleado");

                    b.Navigation("Estado");

                    b.Navigation("TipoHoraExtra");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.SolicitudVacaciones", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empleado");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.TipoConceptoNomina", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaNominaADC.Entidades.ModoCalculoConceptoNomina", "ModoCalculo")
                        .WithMany()
                        .HasForeignKey("IdModoCalculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("ModoCalculo");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.TipoHoraExtra", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.TipoIncapacidad", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.TipoPermiso", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.TipoPlanilla", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("SistemaNominaADC.Entidades.Vacaciones", b =>
                {
                    b.HasOne("SistemaNominaADC.Entidades.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SistemaNominaADC.Entidades.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empleado");

                    b.Navigation("Estado");
                });
#pragma warning restore 612, 618
        }
    }
}
